Re-introduce the "exit" command which will cause builds to fail.
Currently we are still allowing failure for ufront-orm and the API generation.

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -6,7 +6,7 @@
 function stop {
 	PROGNAME=$(basename $0)
 	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
-	#exit 1
+	exit 1
 }
 
 # Compile our docs.
@@ -14,19 +14,21 @@ haxe doc.hxml || stop "Failed to compile API documentation"
 rm -Rf doc/api/*
 mkdir -p doc/api/
 cd doc/
-haxelib run dox -i . -o api/ --title "Ufront-API-Docs" -in . -ex Test$ -t ufront-api/templates/ -res ufront-api/resources/ || stop "Failed to proces API docs"
+haxelib run dox -i . -o api/ --title "Ufront-API-Docs" -in . -ex Test$ -t ufront-api/templates/ -res ufront-api/resources/ #|| stop "Failed to proces API docs" # Currently allowing these to fail.
 cd ../
 
 # Ufront-mvc tests.
 cd submodules/ufront-mvc/
 haxe test.hxml || stop "Failed to compile ufront-mvc tests"
+echo "Test ufront-mvc on Neko"
 neko build/neko_test.n || stop "ufront-mvc tests failed on Neko"
+echo "Test ufront-mvc on PHP"
 php build/php_test.php || stop "ufront-mvc tests failed on PHP"
 cd ../../
 
 # Ufront-orm tests.
 cd submodules/ufront-orm
-./testAll.sh || stop "ufront-orm tests failed"
+./testAll.sh || # stop "ufront-orm tests failed" # Currently allowing these to fail.
 cd ../../
 
 # Compile ufront-hello
